### ISSUE TITLE
Consider type.today's Cyrillic review

### ISSUE THREAD

**Issue by thlinard** [adobe-fonts/source-serif#101]
https://type.today/en/journal/transitional#SourceSerifPro

**Comment by frankrolf** [comment]
Thanks. Are there any specific points you want to make?

<img width="919" alt="asd" src="https://user-images.githubusercontent.com/2049645/140318365-6e3cba63-26aa-4180-adec-17d7b05e757c.png">

The review on type.today does not mention which version is shown, so might well be outdated. The д has been seen some change in the meantime, for example.
As you can read in the credits, Ilya Ruderman was one of several advisors for the Cyrillic of this project, so I would be surprised if his own public assessment would raise more details than he already communicated to me.

**Comment by thlinard** [comment]
Hi @frankrolf 

The point? Bringing this up to your attention. If you've read it already, great!

> The review on type.today does not mention which version is shown, so might well be outdated. The д has been seen some change in the meantime, for example. As you can read in the credits, Ilya Ruderman was one of several advisors for the Cyrillic of this project, so I would be surprised if his own public assessment would raise more details than he already communicated to me.

I looked at the д for version 4.004, is there a newer version? For this version, the review is still valid. But if this review has already been communicated to you, so much the better.
