### ISSUE TITLE
Bulgarian alternates

### ISSUE THREAD

**Issue by jsacouncil** [adobe-fonts/source-serif#104]
Hello,

I'm using Source Serif for a project in InDesign with a text in Bulgarian. When I mark "Bulgarian" in the language selector of InDesign (sample 2), there is character substitution. Could you let me know if there is a way to mark the text as "Bulgarian" and display the script as in sample 1?

Thank you!

Jos
![1](https://user-images.githubusercontent.com/104826852/166432159-c6a19779-8e1a-4cbb-8469-5bca19148e68.png)
![2](https://user-images.githubusercontent.com/104826852/166432166-71027f03-1edb-4822-a904-9533a3faabab.png)
e

**Comment by frankrolf** [comment]
Source Serif is localized for Bulgarian – unless I am missing something obvious, these characters are the preferred shapes for setting Bulgarian text:
https://www.fontsmith.com/blog/2016/10/12/cyrillic-script-variations-and-the-importance-of-localisation

**Comment by jsacouncil** [comment]
Hi Frank, thanks a lot for the clarification.
