### ISSUE TITLE
Is there's any plans to add IPA support for the fonts?

### ISSUE THREAD

**Issue by NDPtype** [adobe-fonts/source-serif#106]
The **Source Sans 3** typeface has rich support for IPA, and now I want a version of **Source Serif 4** that also has rich support like that. So can you add IPA support for future versions, please?

**Comment by frankrolf** [comment]
https://github.com/adobe-fonts/source-serif/issues/22

**Comment by NDPtype** [comment]
Thanks. I think you should study the design of other serif fonts with IPA support.
