### ISSUE TITLE
L·L is tight in some styles

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif#109]
In some styles, the contextual kerning triplet for L·L is tighter than the default LL pair:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/2049645/202467320-01a1c73f-ae48-420e-b512-52a35a2b3e22.png">

https://github.com/adobe-fonts/source-serif/issues/15#issuecomment-413929491

**Comment by erkinalp** [comment]
yeah, L and L kemmed by ·
