### ISSUE TITLE
Collision avoidance for Lithuanian letters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-serif#115]
I think there are some necessaries to implement collision avoidance to certain Lithuanian letters as they can overlap each other, for example, in the word Sąjūdis, a-ogonek can overlap _j_ a bit. So you need to implement either kerning or contextual alternates for fix.

**Comment by frankrolf** [comment]
In my opinion, the possibility for overlaps is one of the big advantages of digital type. In bolder weights, you will also find an overlap in the word `Typography`, for example. Any kerning to avoid the collision between `ą` and `j` would result in uneven spacing, which I find much worse than the occasional overlap.

**Comment by kenmcd** [comment]
@KrasnayaPloshchad 
Do you know of any fonts which have actually done this?
I would like to see examples of how it was handled.

**Comment by frankrolf** [comment]
I know that [Vesper by Mota Italic](https://www.motaitalic.com/product/vesper/) avoids collisions by employing contextual alternates.

**Comment by kenmcd** [comment]
> I know that [Vesper by Mota Italic](https://www.motaitalic.com/product/vesper/) avoids collisions by employing contextual alternates.

Thanks. 
I took a look at the version I have (v1.505).
It does have `calt` for some characters like their example "Curvy."
But the `ąj` in "Sąjūdis" is only affected by kerning.
And you are right - the big gap looks bad.

**Comment by KrasnayaPloshchad** [comment]
Here is what I’ve seen, reproduced with LibreOffice Writer.
[![2.png](https://i.postimg.cc/DfdRLt2C/2.png)](https://postimg.cc/hhvCqZQx)
[![3.png](https://i.postimg.cc/rFfbYxRx/3.png)](https://postimg.cc/7fTm5CVZ)

**Comment by kenmcd** [comment]
> Here is what I’ve seen, reproduced with LibreOffice Writer.

What I mean is examples of fonts which have done something to avoid the collision. To see how they handled it. With just kerning? (Not a good solution.) Or did they make alternate glyphs and use calt, or something else?
Do you have any working examples?
