### ISSUE TITLE
Source Serif 4 looks like rectangles on Google Fonts

### ISSUE THREAD

**Issue by ScribbleGhost** [adobe-fonts/source-serif#117]
Why does Source Serif 4 look like this in Google Fonts? This happens both on Windows 10 and on Android.
![2023-03-30_12-03-56](https://user-images.githubusercontent.com/49068170/228803849-49e41b3a-927a-46a7-9d14-da3b1cd95a8f.png)

**Comment by frankrolf** [comment]
This does not seem to be a font issue, potentially an issue with the font loading. If this persists after clearing browser cache, please bring up the issue with https://github.com/google/fonts/issues
