### ISSUE TITLE
Severe hinting issues on web fonts

### ISSUE THREAD

**Issue by vitorsr** [adobe-fonts/source-serif#121]
Affects all Chromium browsers on a pristine Windows 11 image.

![https://adobe-fonts.github.io/source-serif/](https://github.com/adobe-fonts/source-serif/assets/40741601/f42d2bcf-b7d3-465b-994e-8cc5d90ab274)

Cause: [SourceSerif4Variable-Roman.otf.woff2](https://adobe-fonts.github.io/source-serif/fonts/VAR/SourceSerif4Variable-Roman.otf.woff2) is loaded instead of [SourceSerif4Variable-Roman.ttf.woff2](https://adobe-fonts.github.io/source-serif/fonts/VAR/SourceSerif4Variable-Roman.ttf.woff2)... which in turn appears to not have hinting.

**Comment by frankrolf** [comment]
Thank you – this is a known issue, see #114.
Source Serif is the first CFF2 font to be hinted, so some weirdness is to be expected :-)

In the meantime, If you need Source Serif VF, I recommend using the (unhinted) TTF for the time being.

**Comment by frankrolf** [comment]
@vitorsr May I ask you to make the same screenshot on a recent version of Chrome? The bug should be fixed.

**Comment by vitorsr** [comment]
Thanks. I have made the same screenshot and it appears to be mitigated.

![](https://github.com/adobe-fonts/source-serif/assets/40741601/0855e6b0-b588-4f24-ba8c-9b200e00e658)

However I should note that hinting is still off for some opsz and wgth variations such as opsz=8 wght=700 in the example below. Moreover it does not seem to be specific to Windows as Chromium’s Skia renderer appears to use FreeType’s CFF2 driver.

|                                          Windows 11 Pro 22H2                                          |                                          Ubuntu 22.04.3 LTS                                           |
| :---------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------: |
| ![](https://github.com/adobe-fonts/source-serif/assets/40741601/2ce8b1c2-6766-407d-ba08-e66994b6195d) | ![](https://github.com/adobe-fonts/source-serif/assets/40741601/02923539-d52b-44f9-8231-0f0f24769465) |

**Comment by frankrolf** [comment]
Thank you for your help!

**Comment by skef** [comment]
The fix for the more recent problem, which was committed to FreeType's source base last December, is now part of FreeType 2.13.3, released on August 12th. Once this gets into a released version of Chrome we'll retest.

**Comment by vitorsr** [comment]
Thanks @skef, I am a big fan of your work!
