### ISSUE TITLE
Request: Dotted zero

### ISSUE THREAD

**Issue by GabrielMiceli** [adobe-fonts/source-serif#123]
Source Sans has three different types of zero glyph, one of which is a [dotted zero](https://github.com/adobe-fonts/source-sans/blob/d183de9bfa3d8d826d1f9016e802d44c3a4a46a5/familyGSUB.fea#L1844-L1854) and is my preferred appearance of the zero. Source Serif already has empty and slashed zeros, but I would like to see the inclusion of something like zero.dot and zero.lfdot in it as a stylistic set, especially since, from what I've found, very few serif fonts do this, and the only one of those that I'd consider "usable" is a bit too wide for my liking.

**Comment by frankrolf** [comment]
Hi Gabriel – thank you for your suggestion.

The `zero` feature (replacing an unfilled zero with a slashed or dotted one) is a feature for environments where `O` and `0` are likely to be confused. This means monospaced terminal/coding fonts, the font printed on your passport, etc.

In serif fonts, the zero is usually easily distinguished from the O by proportion and size. As such the `zero` feature in Source Serif (and many other serif fonts) is actually quite superfluous.

Adding a dotted zero to Source Serif would be a design challenge – serif fonts usually have higher contrast than sans serif designs, so the dot might make that alternate zero stand out very quickly.

I personally don’t think adding a dotted zero to Source Serif would be a design improvement.

**Comment by GabrielMiceli** [comment]
Fair and true. I just think that a dotted zero is just generally aesthetically pleasing for some reason, and I'm not afraid to admit that I'm like one of the few people on Earth who would want this type of thing, so I understand the rationale behind not having one. After all, it really isn't like skinny zeros don't do the job well enough. I just would have liked to have the option of having one much like the slashed zero.
Thank you for your hard work on Source Serif, by the way.
