### ISSUE TITLE
Missing fí (f+í) ligature

### ISSUE THREAD

**Issue by Lululalu** [adobe-fonts/source-serif#126]
This letter combination is pretty common in Portuguese, in words like fígado, física, and fíbula.
![Screenshot 2023-09-02 at 23 17 04](https://github.com/adobe-fonts/source-serif/assets/32398857/32e9fcab-95bd-46d4-bfdb-5e3a5ff0a7ec)

**Comment by frankrolf** [comment]
Ligatures exist to solve a clashing problem, which I do not see in Source Serif. Do you have other examples (weights) where this is more problematic?

Maybe it’ll become more obvious if we see this combination in the context of your example words.

FWIW, I find the ligatures in Literata quite tight, and the fí visually busy.

**Comment by frankrolf** [comment]
Okay, I was curious, so I did the following – I picked 15 of the most common Portuguese words from [this repo](https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/pt/pt_50k.txt), removed obvious pluralizations, (and removed `esfíncter`), and wrote a little DrawBot script ([fí_test.zip](https://github.com/adobe-fonts/source-serif/files/12515084/fi_test.zip)) to come up with this:




![SourceSerif4Variable-Roman otf](https://github.com/adobe-fonts/source-serif/assets/2049645/26e4d31c-a348-4452-ac26-89c59dd77c00)
![Literata-VariableFont_opsz,wght ttf](https://github.com/adobe-fonts/source-serif/assets/2049645/2afeb42f-61ae-4489-b567-f2c1d5645f53)

![SourceSerif4Variable-Italic otf](https://github.com/adobe-fonts/source-serif/assets/2049645/aa2ccb41-19d8-4c96-9b54-7b6cb45ac8a8)
![Literata-Italic-VariableFont_opsz,wght ttf](https://github.com/adobe-fonts/source-serif/assets/2049645/61b1a6ca-793f-4b31-a56f-1390b0a8f09e)

As suspected, there is no combination where fí is obviously clashing – if anything, a kerning exception could be created for fí to make the combination a little tighter. There is no necessity for a ligature here. The fí in Literata Roman is too tight.

In my opinion, ligatures should be inserted sparingly, and really only exist if there’s an obvious problem. On page 4, you’ll see why – it seems that the fí ligature in Literata Italic has been forgotten in a kerning group (unrelated to the problem, just one of the areas where ligatures are more trouble than they’re worth).
