### ISSUE TITLE
Small caps kerning

### ISSUE THREAD

**Issue by schombert** [adobe-fonts/source-serif#128]
When turning on small caps with smcp, I have noticed that some of the small capital letters seem to not kern with each other optimally. In particular, av (AV) seems to be unkerned. Or at least, I think this is what is happening. It could also be that the software for rendering the text isn't handling the kerning properly with smcp on (if this is the case please let me know and I will redirect the problem appropriately).

**Comment by frankrolf** [comment]
A screenshot says more than a thousand words. Small Caps are kerned to capital letters, but of course there may be mistakes.

**Comment by schombert** [comment]
![image](https://github.com/adobe-fonts/source-serif/assets/22087402/a7e03354-c3bd-4545-9c1f-b346313a3982)
Here is what it looks like when I use them as button labels (using smcp).

**Comment by frankrolf** [comment]
Ha, cool use! :-)

I get this on my end, so something seems off with the implementing environment:
<img width="1630" alt="image" src="https://github.com/adobe-fonts/source-serif/assets/2049645/bb4e8f6d-cd98-4ba4-98fc-93dda9605b27">

**Comment by schombert** [comment]
Thanks. I will redirect the problem to elsewhere (probably freetype, since it isn't returning the correct kerning between the glyphs). Love the font BTW; it is becoming my default choice for a lot of things.

**Comment by schombert** [comment]
So I did some more digging, and it turns out that freetype doesn't natively support kerning when it is encoded in the newer opentype tables, and only supports it for legacy ttf kerning information. I am not in a position to switch away from freetype or use one of the more full-featured libraries built on top of it at the moment. So instead I hand rolled some routines that grab the more easily accessible information out of GPOS. With that in place, I managed to get the rendering to look like the following: 
![image](https://github.com/adobe-fonts/source-serif/assets/22087402/ac6c9b57-d9fe-4f63-9674-19f0c681366b)
I don't think it is quite perfect, but it is at least not totally disfigured.

**Comment by frankrolf** [comment]
I think this looks great, much better than the original!
From [freetype.org](https://freetype.org/freetype2/docs/glyphs/glyphs-4.html):
> Note that OpenType fonts (OTF) provide two distinct mechanisms for kerning, using the ‘kern’ and ‘GPOS’ tables, respectively, which are part of the OTF files. Older fonts only contain the former, while recent fonts contain both tables or even ‘GPOS’ data only. FreeType only supports kerning via the (rather simple) ‘kern’ table. For the interpretation of kerning data in the (highly sophisticated) ‘GPOS’ table you need a higher-level library like [ICU](http://icu-project.org/) or [HarfBuzz](http://harfbuzz.org/) since it can be context dependent (this is, the kerning may vary depending on the position within a text string, for example).

It’s a bit unclear what “older” and “recent” means in this context, but fonts today cannot make do with a `kern` table alone (this has been true for several decades). It would make sense for you to also use harfBuzz, which will give you not just glyph rasterization (FreeType’s job), but also full access to OpenType features.
