### ISSUE TITLE
White hole in fi ligature

### ISSUE THREAD

**Issue by ghost** [adobe-fonts/source-serif#130]
There seems to be a small white hole in the fi ligature in the "head" of the f. (Not sure about the correct term.)

![grafik](https://github.com/adobe-fonts/source-serif/assets/13430670/e1aaa01d-de37-4b73-af24-42643cf53d58)

- SourceSerif4-Regular.ttf, version 4.004
- On win 11, using sumatra pdf or word

**Comment by kenmcd** [comment]
Which specific font?
Which version of the font? 
What application are you using where you see this?
And what version of that application?
What operating system, and version?
Please provide a screenshot of what you are seeing.

**Comment by ghost** [comment]
Edited the issue description accordingly.

**Comment by kenmcd** [comment]
That is part of a looped corner used for proper interpolation in variable fonts (also called overlaps).
Looks like you are using the Google Fonts (GF) version of v4.004.
GF leaves the overlaps in.
The fonts in the releases here in the repo have the overlaps removed from the static fonts.
So get the current v4.005 release from here:
https://github.com/adobe-fonts/source-serif/releases/tag/4.005R
The static TTF fonts will work for you.
Also, OTF static fonts never have overlaps.
So you could also just use the OTF static fonts from the release.

**Comment by ghost** [comment]
I see! You are right, the alternatives are fine.

**Comment by frankrolf** [comment]
Thanks for your help @kenmcd! 👍
