### ISSUE TITLE
Optical Sizes

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif#57]
@ReymundS and @late2game will handle the extension of Source Serif into optical sizes Display and Caption. This issue is for tracking the work, and for answering any questions.

**Comment by RuixiZhang42** [comment]
Since Source Serif Pro Math https://github.com/adobe-fonts/source-serif-pro/issues/13 is also on the roadmap, it would be nice to also include a “Tiny” optical size for the second-order sub/superscripts as well (Caption could be used for first-order sub/superscripts).

I’ll add some links to the Source Serif Pro Math thread.

**Comment by frankrolf** [comment]
Thank you for the kickoff meeting today, Reymund and Thomas! 
Here are the scale values I used to prepare the first step toward Caption- and Display masters:
https://gist.github.com/frankrolf/44ebc3c8157bef1591e0174d95fe09a6

**Comment by frankrolf** [comment]
This is the `normalizeAll` shell script I use: https://github.com/adobe-type-tools/shell-scripts.
UFOnormalizer needs to be installed, which can just be done using `pip` or `pip3` (see instructions here: https://github.com/unified-font-object/ufoNormalizer )

**Comment by ReymundS** [comment]
• Frank recommends an adaptation/modulation of the (head)serifs in both  »Caption« and »Display«.
• »Caption«: Inktraps in the bold version to be proofed.
• Frank basically agrees with the proposals for f, g, t, ß as well as the cyrillic “d”, “l” – but also with the basic parameters.

[Source Compare.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3325613/Source.Compare.pdf)

**Comment by frankrolf** [comment]
You brought up an interesting point with the relationship of Д vs Л. I discussed this screenshot with Maria Doreuli, see below what she has to say:
![Screen Shot 2019-06-25 at 14 20 53](https://user-images.githubusercontent.com/2049645/60348059-17496500-99bf-11e9-95fe-e8b0c3b2cd58.png)
> I find the right one better related to the Л and I think it makes sense. Although to my eye the left side of the right version of the Д is a little too static and the bottom left horizontal segment a little too short.
> The new form will help to avoid a large space on the left of the glyph and also perform better in Bolder weights 
> The left stroke should still be rather diagonal than vertical

So while the modification is welcome, it needs to be less heavy-handed – please make sure the left stroke still curls, has some kind of diagonality, and please don’t shorten the platform of the “teeth”.

----

Concerning the horizontal top of those teeth – I was thinking about this a lot, and I actually think it’s counter-productive to make them look exactly like the serifs. The weight needs to be present, and filing on the top removes quite a bit of it. What I would suggest instead is making other occurences of the vertical teeth horizontal, or at least thicker on top. Here are some examples from other typefaces:

![Screen Shot 2019-06-28 at 16 15 49](https://user-images.githubusercontent.com/2049645/60348592-2da3f080-99c0-11e9-883f-509c0b081925.png)
![Screen Shot 2019-06-28 at 16 15 35](https://user-images.githubusercontent.com/2049645/60348593-2e3c8700-99c0-11e9-9d8b-8f77c06f6d59.png)

**Comment by late2game** [comment]
Glad Maria approved the quick and dirty proposal.

I tried to follow her instruction and made the left stroke a bit more diagonal and got back to the original teeth. I also tried to streamline the dot droplets so that they evolve a bit better throughout the weights.
Maybe you should show this to Maria again to be sure that we are on the safe side.
The SC are still to be done, but I'd like to have your and/or Maria's GO before I continue.

Below are 2 screenshots that show the result for all 3 roman weights for UC and LC as well as a PDF for closer inspection.

![Source Cyr De + El](https://user-images.githubusercontent.com/44244388/60428021-3d0d7e80-9bf8-11e9-9da8-b38c998fdb2d.png)
![Source CYR De + El 2](https://user-images.githubusercontent.com/44244388/60428306-d9378580-9bf8-11e9-83a9-0f4a0b12beba.png)
[Source Serif CYR De + El.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3345024/Source.Serif.CYR.De.%2B.El.pdf)

**Comment by late2game** [comment]
We already had a quick chat on the ending of the LC terminals and I'd like to share this here.
We agreed that it's a good idea to have the terminals ending straight for Display, but we didn't agreed if all should end straight or only the top terminals of m, n, p, r. 

![Source LAT terminals](https://user-images.githubusercontent.com/44244388/60428573-6a0e6100-9bf9-11e9-86db-1d5a92275c7c.png)
[Source Serif  LAT terminals.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3345070/Source.Serif.LAT.terminals.pdf)

**Comment by frankrolf** [comment]
Since Source Serif follows Fournier in some (not all) decisions, I think it makes sense to consult the source material in this case. Here is an example:
![2013-06-22_193153](https://user-images.githubusercontent.com/2049645/60435082-ea888e00-9c08-11e9-9ac7-fdcb616ddcb7.jpg)

As we can see here, most top terminals are straight, some even slightly angled forward.
Angled top terminals are a good idea in text sizes to avoid clumping, but since you are working on the display style, I agree it sounds like a good idea to straighten them.
One thing I’m noticing though – in the `p` it looks like the incision from stem to bowl became shallower – is that an optical illusion, or a deliberate change? I think it needs to be a little deeper (compare w/ `n`).

**Comment by late2game** [comment]
Ok, so we make all terminals straight. The difference in incision is deliberate since it appears in the text, but it seems that it gets more obvious with straight terminals.
See screenshot below left = text, right = display.

![np - incision](https://user-images.githubusercontent.com/44244388/60437147-03477280-9c0e-11e9-9c6e-ac9781508d5d.png)

**Comment by frankrolf** [comment]
Concerning ДЛ - here are comments from Maria:
![Source Serif CYR De + El](https://user-images.githubusercontent.com/2049645/60492941-3d675180-9cac-11e9-91f6-35675b85c048.png)

[Source.Serif.CYR.De.+.El.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3348812/Source.Serif.CYR.De.%2B.El.pdf)

**Comment by late2game** [comment]
All her comments make sense and will be implemented these coming days. I'm surprised we even got a "nice" from her, that's not very common with native speakers.

**Comment by ReymundS** [comment]
As a visual reference for the first commit there is the following PDF showing UC and LC (all upright masters) in both »Caption« as well as »Display«.

[Source Serif C-D.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3372279/Source.Serif.C-D.pdf)

**Comment by frankrolf** [comment]
Dear @ReymundS and @late2game, thanks very much for your work!
It all looks very promising, and I think we are going in the right direction on either end of the spectrum.
One of the largest changes I propose is that the Black display master could maybe even get a little more contrast.

I have marked up a few things in the PDF proof, see here:
[Source Serif C-D_marked up.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3386622/Source.Serif.C-D_marked.up.pdf)

**Comment by late2game** [comment]
Dear @frankrolf, thanks for the fast and productive feedback!
The increased contrast in Black is quite beneficial.
Before I'm going to make another commit to Display I'd like to show you a PDF that has all the latest changes. Please, have closer look on the last 3 pages where I've some doubts. 

You can find the latest Display PDF here:
[Source Serif Display update.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3393009/Source.Serif.Display.update.pdf)

**Comment by frankrolf** [comment]
![Untitled](https://user-images.githubusercontent.com/2049645/61288282-15591180-a7c7-11e9-8593-61c86704ab6b.png)

Here I was pointing out two things:
- in the lightest display master, the curve where the leg turns into the serif is very small, making it look like a corner. It might be possible to make that change of direction somewhat smoother, perhaps by shaving off some mass from the “heel” of the leg on the left side.
- the legs in general seem very timid in the display masters. Especially at large sizes, they can become a bit more self-assured and longer – I would move all of them to the right a little, and angle them out slightly more.
- a thing I did not point out but which needs attention: cleaning up the junction area on the right outside of the glyph, where the bowl meets the leg in the heaviest display master. There is a lot of dark there, which could be lightened.

![Untitled2](https://user-images.githubusercontent.com/2049645/61288365-3de10b80-a7c7-11e9-83c6-0c54f52daccc.png)

I think I might have been commenting on the bad rasterization of my printout here: 
![Scan 1](https://user-images.githubusercontent.com/2049645/61288772-1e96ae00-a7c8-11e9-8c60-faf171585bc5.jpg)

Still, In the heaviest display master, I feel the top curve of the bowl coming out of the stem has an ever-so-tiny little upward swelling. Maybe it can be straightened out?

![Untitled3](https://user-images.githubusercontent.com/2049645/61288954-80efae80-a7c8-11e9-8d99-5664ba4f8c91.png)

I was seeing this in context with the `e`, and I felt there was a visible difference.
Ironically, it looks thicker blown up like this:
![Scan](https://user-images.githubusercontent.com/2049645/61289031-ada3c600-a7c8-11e9-995d-18244e02e209.jpg)

Let’s keep an eye on this one, no need to change anything for that `w` right this moment.

**Comment by FloraCanou** [comment]
I have an idea, just for reference. Higher contrast in letter widths contributes positively to the title type, as is explicitly commented by Akira Kobayashi in his book _European Fonts II_. 

Currently the O and E have basically the same width, which is good for text size, but that looks forced for Display. Thus, it could be favorable for letters like C, D, G, M, O, Q, W to be made wider.

**Comment by frankrolf** [comment]
@FloraCanou Thanks for the suggestion! We will consider it.

**Comment by ReymundS** [comment]
Reworked and streamlined basic roman alphabet ( UC / LC ) according to the last review as well as the first italic proposal to match the new romans. 
—
»Caption«: optimized details, optimized proportions, interpolatet testweights
»Display«: optimized contrast, optimized serifs, optimized proportions

[Source Serif UC-LC.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3455991/Source.Serif.UC-LC.pdf)

**Comment by frankrolf** [comment]
Dear Reymund and Thomas,
thank you for your work! I’m very happy with how the project is progressing, and have only a few things to say:

[Source.Serif.UC-LC_abridged_annotated_fg.pdf](https://github.com/adobe-fonts/source-serif-pro/files/3524666/Source.Serif.UC-LC_abridged_annotated_fg.pdf)

**Comment by frankrolf** [comment]
Design-Modifikationen Caption Roman

- [ ] Winkel und Masse der Tropfen im Vergleich zu anderen Größen angleichen (z.B. csє, Kyrillischer Breve-Akzent)
- [ ] Tropfen in j etwas verkürzen
- [ ] Allgemeine Verkürzung der Kyrillischen Tropfen (zB ЛЉѴлмљѵ)
- [ ] alpha: aufrechten Winkel der Roman übernehmen
- [ ] schwa etwas besser ausbalancieren
- [ ] offensichtlichere Caption-Versionen zu †‡§&*£₴ ₺
- [ ] Lslash/lslash eventuell auch mit ink trap? 
- [ ] arrow: vielleicht wäre es gut, hier keinen Kontrast zu verwenden, und dafür 2 inktraps einzubauen) [?]
- [ ] eighthnote: ganz wichtig: caption [?]
- [x] inktraps in Großbuchstaben (auch Kyrillisch und Griechisch, e.g. ΔΛΣИУ)
- [x] inktraps in Ziffern
- [x] zusätzliche inktraps in Kleinbuchstaben (zB kxzδζλχ)
- [x] Optische Korrektur der Punze in Øø /zero.slash / Oslash.sc
- [x] Optische Korrektur der Punze in Өө
- [x] Ohorn: Platzierung des Horns überprüfen, Hornspitze abrunden
- [x] Verinktrapptes Ogonek
- [x] eventuell leichte vertikalisierung der Serifen in SsTCG – das ergibt einen größeren Innenraum
- [x] spacing verschiedener double-quotes öffnen, zB guillemet oder quotedbl (eventuell schon geschehen)
- [x] kleine Ziffern in master_2 sind extrapoliert und müssen überarbeitet werden
- [x] Grundlinie der Nenner in _0 korrigieren
- [x] J.sups in _2 verkürzen
- [x] perthousand: hier sieht man die Extrapolation der kleinen Ziffern sehr gut
- [x] infinity: Kontrast
- [x] integral: in Master_2 etwas nach vorne lehnen
- [x] estimated: muss leider generisch bleiben
- [x] Bessere inktraps in ҚҖ Master_2
- [x] ghestroke/Ghestroke -- mittelstrich generell etwas verlängern (siehe auch Display)
- [x] Sigma.sc im schwersten Master etwas besser balancieren
- [x] Ә oben rechts allgemein etwas besser ausarbeiten
- [x] leichte Gewichtsverlagerung in ч (gg. 7 Uhr)


Design-Modifikationen Caption Italic

- [ ] Winkel der bauchigen Kleinbuchstaben (abcdegpqsxz in Master_1 etwas mehr neigen
- [ ] inktraps in Großbuchstaben (auch Kyrillisch und Griechisch, e.g. ΔΛΣ)
- [ ] inktraps in Ziffern
- [ ] zusätzliche inktraps in Kleinbuchstaben (kxzδζλχғ)
- [x] Verkürzung des J
- [ ] Winkel und Masse der Tropfen im Vergleich zu anderen Größen angleichen (z.B. csf)
- [ ] Kommaakzent leicht entspitzen
- [ ] Allgemeine Verkürzung der Kyrillischen Tropfen 
- [ ] Optische Korrektur der Punze in Øø /zero.slash 
- [ ] Optische Korrektur der Punze in Өө
- [ ] Details in æœ 
- [ ] offensichtlichere Caption-Versionen zu †‡§*£₴ 
- [ ] Verinktrapptes Ogonek
- [ ] Lslash/lslash eventuell auch mit ink trap?
- [ ] eventuell leichte vertikalisierung der Serifen in STCG – das ergibt einen größeren Innenraum
- [ ] Mitte in kgreenlandic/ka optisch nach unten verschieben
- [ ] spacing verschiedener double-quotes öffnen, zB guillemet oder quotedbl (eventuell schon geschehen)
- [ ] Grundlinie der Nenner korrigieren
- [x] infinity: Kontrast
- [x] estimated: muss leider generisch bleiben
- [x] Be: Arm verlängern
- [ ] Allgemein in den Kyrillischen Kleinbuchstaben etwas das Gewicht »in die Ecke« verschieben  – в/ve.bgr/hard.bgr/soft.bgr/che.bgr)
- [ ] Ә oben rechts allgemein etwas besser ausarbeiten

**Comment by frankrolf** [comment]
Design-Modifikationen Display Roman

- [ ] Schultern von đ & ħ + Mittelstrich des Ħ/Hbar.sc optisch balancieren
- [ ] Optische Korrektur der Punze in Øø /zero.slash / Oslash.sc Ө Obarcyr.sc ө
- [ ] Akzente im schwersten Master etwas kleiner
- [ ] Akzente je Master allgemein etwas mehr aufeinander abstimmen
- [ ] tiefere Einschnitte in æœ Master 2
- [ ] schwa etwas besser ausbalancieren
- [ ] cedilla: Kontrastmodell an andere Größen angleichen
- [ ] tildecmb/tildecmb.cap: kann etwas dynamischer werden
- [ ] alpha: aufrechten Winkel der Roman übernehmen
- [ ] Я _2 etwas besser balancieren
- [ ] ghestroke/Ghestroke -- mittelstrich generell etwas verkürzen (siehe auch Caption)
- [ ] /question/question.sc/exclam/exclam.sc mehr Kontrast
- [ ] generelle Verkleinerung der Satzzeichen, vor Allem im Master _2

Design-Modifikationen Display Italic

- [ ] Schultern von đ & ħ + Mittelstrich des Ħ optisch balancieren
- [ ] Optische Korrektur der Punze in Øø /zero.slash Өө
- [ ] Verkürzung des J
- [ ] Ring (verwendet im Å, beispielsweise) etwas weniger künstlich verzerrt wirken lassen
- [ ] Akzente im schwersten Master etwas kleiner
- [ ] Akzente je Master allgemein etwas mehr aufeinander abstimmen
- [ ] tiefere Einschnitte in œ Master 2
- [ ] cedilla: Kontrastmodell an andere Größen angleichen
- [ ] tildecmb/tildecmb.cap: kann etwas dynamischer werden
- [ ] Я _2 etwas besser balancieren
- [ ] /question/exclam mehr Kontrast
- [ ] generelle Verkleinerung der Satzzeichen, vor Allem im Master _2

**Comment by frankrolf** [comment]
Design-Modifikationen Text Roman

- [ ] Ordentliches Omega.sc
- [ ] Komma-Winkel harmonisieren
- [ ] Kommaakzent-Winkel harmonisieren
- [ ] N oben links etwas entkrampfen
- [ ] tiefere Einschnitte in æœ Master 2
- [ ] divisionslash wie in der Italic anwenden
- [x] section _2 muss eleganter werden
- [x] g Black etwas eleganter machen
- [x] Abschlussrichtung im c und e angleichen


Design-Modifikationen Text Italic

- [ ] N oben links etwas entkrampfen
- [ ] ohorn Italic_0 mal genau ansehen 
- [ ] tiefere Einschnitte in œ Master 2
- [ ] Das Ampersand in Master 2 muss verbessert werden
- [ ] Komma in _0 etwas verkürzen und harmonischer ausrichten
- [ ] g etwas besser balancieren

**Comment by davelab6** [comment]
What's the current status of this work? :)

**Comment by frankrolf** [comment]
Hi @davelab6, 
@late2game and @ReymundS  delivered their work in the end of March, and ever since I’ve been merging all threads together. 
It takes long as usual, for a detailed list of things I’m doing I recommend peeking at my commit messages: https://github.com/adobe-fonts/source-serif-pro/commits/opsz

The whole family has gone through QE once already, and will again after this week. I predict the completion of my work on this family for August.

**Comment by frankrolf** [comment]
@davelab6 The family is now in its final QE pass, I hope to release the family after that.

**Comment by frankrolf** [comment]
Thanks to the remarkable work of @late2game and @ReymundS, the addition of optical sizes has been completed.
Source Serif now has 60 static styles (instead of 12), and I personally think the optical size axis makes the family a whole lot more versatile. A specimen site like this wouldn’t have been possible before:
https://adobe-fonts.github.io/source-serif/

Thanks again, Reymund and Thomas! 🎉

**Comment by davelab6** [comment]
Amazing work! Thank you Reymund, Thomas, Frank and everyone else who has made this a success :)

**Comment by throwaway571** [comment]
@frankrolf For reference, what point sizes is each optical size designed for?

**Comment by RuixiZhang42** [comment]
@throwaway571 Based on how the static font instances are named, the optical size convention is likely to follow Adobe&rsquo;s in-house recommendation: caption (6-8 point), regular (9-13 point), subhead (14-24 point) and display (25-72 point). See, for example, https://www.adobe.com/ca/products/type/opentype.html

**Comment by frankrolf** [comment]
I will detail this in a blog post, coming soon.
Based on my own testing on the [specimen page](https://adobe-fonts.github.io/source-serif/), I decided on the following sizes:

```
 8pt Caption
16pt SmText
20pt Text
32pt Subhead
60pt Display
```

Master designs exist for 8pt, 20pt, 60pt.
