### ISSUE TITLE
Letters i and j with diacritics, and Soft_Dotted property

### ISSUE THREAD

**Issue by codepointless** [adobe-fonts/source-serif#71]
Latin letters _i_ and _j_ should lose their dot when used with any combining marks above. It is pointed out in the [Unicode standard](https://www.unicode.org/versions/Unicode13.0.0/ch07.pdf) (see section ‘Diacritics on _i_ and _j_’ on page 289 and figure 7-2), and popular fonts follow this practice:
![Times](https://user-images.githubusercontent.com/62960560/78065819-844db900-739c-11ea-8300-5d827d88847e.png)
With Source Serif Pro, I get this instead:
![Source Serif](https://user-images.githubusercontent.com/62960560/78065851-9891b600-739c-11ea-888a-81001f9acdb7.png)

Actually, the same rule also applies to Latin characters
`į ị ⁱ ʲ`
and Cyrillic letters
`і ј`,
since they all have the **Soft_Dotted** property in Unicode (see [PropList.txt](https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt); here I list only characters included in Source Serif). Unfortunately, existing fonts support this property very inconsistently, and Noto seems to be the only font that really [tries to do it right](https://github.com/googlefonts/noto-fonts/issues/418).

**Comment by frankrolf** [comment]
Which environment do you observe this behavior in?

**Comment by codepointless** [comment]
I tried MS Word, and also made HTML and opened it in Firefox. In both cases diacritical marks are rendered correctly only if a precomposed character exists in the font. So, j with combining circumflex looks like ĵ, but j with combining acute looks like... well, see the picture above.

**Comment by frankrolf** [comment]
This is a good time to bring this up – thank you for that.
I will have a look at the feature code, and hopefully fix the problem.

**Comment by frankrolf** [comment]
I fixed the issue for `i j і ј` (Latin and Cyrillic), as well as `į ị`.
There currently is no method in place for combining accents on top of superiors, so I left out `ⁱ ʲ`.

**Comment by frankrolf** [comment]
This is resolved in Source Serif 4.004: https://github.com/adobe-fonts/source-serif/releases/tag/4.004R
