### ISSUE TITLE
Diacritics with Cyrillic letters

### ISSUE THREAD

**Issue by codepointless** [adobe-fonts/source-serif#72]
In Russian and several other languages that use the Cyrillic script, accented syllables can be shown with a stress mark above the vowel. In Source Serif Pro, some vowels with diacritics are rendered incorrectly:
![Буквы](https://user-images.githubusercontent.com/62960560/78200823-8006c600-7498-11ea-8142-70b48afb409e.png)
(I have no idea what’s wrong with the capital letters, I tried both TTF and OTF with the same result.)

For all Cyrillic letters, diacritics should be positioned just above the letter. I suppose _ѣ_ is the least obvious, so here are some examples of _ѣ_ with acute and diaeresis from an old dictionary (when this letter was in use):
![Медвѣдъ](https://user-images.githubusercontent.com/62960560/78201155-95302480-7499-11ea-9c7d-6cf9cca3d810.png)

![Вѣсить](https://user-images.githubusercontent.com/62960560/78201165-9e20f600-7499-11ea-888d-8788ceb209c1.png)

I also have a question: is it possible to make **all** Cyrillic letters look decent with combining marks above and below? I understand that you don’t want to do it manually, but maybe there’s a way to make something passable automatically. It’s true that we don’t use diacritics in usual texts, but sometimes it may come in handy.

**Comment by frankrolf** [comment]
Thank you.
To make sure we are on the same page:

- which are the diacritics that may be added on top of Cyrillic base glyphs? I know of acute, but also see diaeresis in your example. Grave?
- is it also possible to place diacritics _below_ Cyrillic letters?
- it would be possible to make _all_ Cyrillic letters receive combining accents, this is just a matter of preparing the data. However, do you have a list of letter which _may_ receive accents at all?

Notwithstanding all of the above, in the screenshot you provide it looks like the combining acute accent is not used. Note that the combining acute (U+0301) is a non-spacing glyph. Here is an example using the combining acute with the currently shipping fonts, as seen on https://adobe-fonts.github.io/source-serif-pro/ . 
![image](https://user-images.githubusercontent.com/2049645/78231799-a72eb900-74d3-11ea-83d0-085d1358154b.png)
I am not saying this is perfect, but slightly better than the example you’re showing.

**Comment by codepointless** [comment]
Wow, it’s interesting. All small letters in your picture look fine, although I would use the ‘slanted‘ acute for ‘high’ letters like _ѣ_ and _ё_. Of cource I used the combining acute (U+0301), and the spaces you see are real spaces (U+0020). And that’s what I see in four different browsers:
![Small letters](https://user-images.githubusercontent.com/62960560/78284547-4087ba80-7528-11ea-8e4c-e4e83c11c87b.png)
Can it be some Windows-related issue? Can you explain what internal mechanism is used to raise the acute and place above the letter _б_ in your picture? Maybe it could help me understand what exactly goes wrong on my computer. The capital letters are the most mysterious cos I get this:
![Capital italics](https://user-images.githubusercontent.com/62960560/78286070-75484180-7529-11ea-9084-dd42dcb6536d.png)

Now, about combining marks in Cyrillic script.

The letter _ѣ_ with two dots above is rather a typographical experiment than a conventional letter, and it’s not the most strange thing I’ve seen in Russian books from the beginning of the last century. These experiments were soon stopped by communists who removed _Ѣ_ from Russian alphabet.

As far as I know, diacritics are not actively used in all modern languages with Cyrillic alphabets (except if they are part of letters like _й_ and _ќ_, of course). Some Slavic languages use cobining marks to show word accent. In Russian, we use acute for primary stress and grave for secondary stress, they can be put above vowels only. I’m quite sure the same is true for Ukrainian, Belorussian and Rusyn, and here’s the list of our vowels:
`Аа Ее Ёё ЄЄ Ии Іі Її Оо Уу Ыы (Ѣѣ) Ээ Юю Яя (Ѵѵ)`
(Ѣ and Ѵ are not currently in use).

In Bulgarian, accented vowels are denoted by grave (or sometimes by acute), and the letter
`Ъъ`
is also a vowel, so it also can be stressed:
![жъртва](https://user-images.githubusercontent.com/62960560/78305362-62456980-7549-11ea-86fc-db06b63682a6.png) ![дъно](https://user-images.githubusercontent.com/62960560/78305372-683b4a80-7549-11ea-8cb6-4b5169b3b4a2.png)
Perhaps Macedonian uses grave in the same way, but I’m not quite sure.

Serbs have much more fun with their pitch accent. They use acute, grave, double grave, inverted breve and macron above vowels and syllabic consonants (I’ve seen accented _р_, but probably there are other consonants):
![братан](https://user-images.githubusercontent.com/62960560/78307520-c1f24380-754e-11ea-8893-8b19f0a99110.png) ![брз](https://user-images.githubusercontent.com/62960560/78307526-c6b6f780-754e-11ea-830d-2f200b33feb7.png)
There’s also Montenegrin language... Let’s hope they didn’t invent something else.

Besides Slavic languages, there are many non-Slavic languages that use Cyrillic script. They have plenty of interesting letters like _Є̈_, _И̃_ and _Ю̆_ that aren’t presented in Unicode and have to be composed from letters with diacritic marks. Some list of those letters can be found on [Wikipedia](https://en.wikipedia.org/wiki/Template:Infobox_Cyrillic_letter), it also includes some letters with diacritics _below_ (such as [_Г with cedilla_](https://en.wikipedia.org/wiki/Ge_with_cedilla), but I can’t guarantee this information is correct.

This was about usual texts. But when it comes to linguistics, I would expect _everything_. Russian letters are used in Russian phonetic notation. This is what can happen to vowels:
![Vowels](https://user-images.githubusercontent.com/62960560/78310742-8740d900-7557-11ea-859f-b8f63bd206ec.png)
And this is what can happen to consonants:
![Consonants](https://user-images.githubusercontent.com/62960560/78310812-accde280-7557-11ea-805b-ea53b4abd5de.png)
This is transcription of Czech words (in italics):
![чешский](https://user-images.githubusercontent.com/62960560/78311100-92483900-7558-11ea-84b8-4b9db437f9cb.png)
And this is transcribed passage in Rusyn dialect I’ve just [found on Wikipedia](https://ru.wikipedia.org/wiki/Русинский_язык#Верховинский_диалект):

> Мốї ма́мi. Нно, та в’ĭн мно́го чếляде так шчо.. обы̊́ хво́рi бы̊́ли. 

By the way, this ы̊́ also looks wrong in my browser (in Arial), so maybe something _is_ wrong with my computer...

**Comment by frankrolf** [comment]
Thank you so much for all this! To answer your questions:

>Can you explain what internal mechanism is used to raise the acute and place above the letter б in your picture?
- The internal mechanism used is the `mark` feature, which defines a group of base glyphs, and which combining accents those may be joined with. Inside the font source, this communication happens through assignment of anchors.

> Can it be some Windows-related issue?
- I don’t know. Possibly? But AFAIK Windows should support the mark feature – depending on the application, of course.

> The capital letters are the most mysterious cos I get this:
- The anchors were unified between Roman and Italic in d6f806e, any version following that commit should have those anchors in place. Generally, I recommend using the latest version of the fonts – are you sure you are testing with https://github.com/adobe-fonts/source-serif-pro/releases/tag/3.001R ?

All that said, I am not sure why all lowercase letters show semi-accurate positioning of the combining mark. It may well be there’s some macOS magic going on (I am using Safari 13.1). When I make a similar test in InDesign, the outcome is more in line with what I expect, based on anchors in the UFO files:
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/2049645/78552171-4c64cc80-7807-11ea-83b8-4b16a22c478a.png">

One more remark:
I don’t expect any use of combining accents above already-accented glyphs such as `ёїйќ`, but will prepare anchors for non-accented base glyphs.

**Comment by codepointless** [comment]
Yes, I’ve installed the latest version of the font. Moreover, the [test page on guthub](https://adobe-fonts.github.io/source-serif-pro/) uses its own web-font and doesn’t give me a choice, right? Did you try accented italic capital letters in InDesign? It looks like some bug in the font, because accented Latin letters (even not precomposed) look fine.

> I don’t expect any use of combining accents above already-accented glyphs such as `ёїйќ`

These are separate letters, so they can also be used with diacritics above (especially `ё` and `ї`, since they are vowels):
![четырёхвёсельный](https://user-images.githubusercontent.com/62960560/78578312-02e0a580-7838-11ea-95bf-a77e7cca1fd3.png)
In the last picture in my [previous comment](https://github.com/adobe-fonts/source-serif-pro/issues/72#issuecomment-608164621), you can see _й́_ in phonetic notation.

**Comment by throwaway571** [comment]
Related to this, the Montenegrin spelling standard, sometimes considered a separate language for political reasons, may use the letters `С́ с́` and `З́ з́` for palatalized sibilants spelled `сј` and `зј` in other varieties of Serbo-Croatian.

**Comment by frankrolf** [comment]
The latest release of Source Serif has better support for adding combining marks to Cyrillic base characters:
https://github.com/adobe-fonts/source-serif/releases/tag/4.004R

**Comment by codepointless** [comment]
Now diacritics above work correctly with Cyrillic vowels, but there’s still at least one bug.

If ё is combined with diacritics, it looks like ӥ. For example, the sequence ё́ (U+0451 U+301) gives this:
![ё́](https://user-images.githubusercontent.com/62960560/105976998-1278f580-60bb-11eb-8ed7-e8426f49a9b6.PNG)

**Comment by frankrolf** [comment]
Wow, that’s something! Thanks for the report!
I am opening a new bug for this.

**Comment by codepointless** [comment]
Thanks. By the way, are there absolutely no plans to add anchors to consonants and anchors for combining marks below?

**Comment by frankrolf** [comment]
When I worked on this addition, I considered adding anchors to the consonants too – but I did not know where I’d stop with that, so I kept it at vowels.
Source Serif does not even support linguistics (IPA) for Latin yet, so a focus on linguistic use in Cyrillic could be part of a future update.
