### ISSUE TITLE
PSA: font family name will change

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-serif#77]
With Source Serif’s optical sizes on the horizon, the decision was made to change the family name to **Source Serif 4**.

The reason is twofold:
- avoid the name **Pro** (which used to stand for an extension from Basic Latin AL1 to CE-compatible character set AL2). Source Serif much exceeds AL2, therefore Pro does not really mean anything.
- avoid metrics incompatibility in comparison with older versions. To make the building of the VF more reliable, the location of the default master has changed, which may result in small advance-width differences across font versions.

The family name going forward will be **Source Serif 4**, which corresponds to the current global version number.

**Comment by charakterziffer** [comment]
I respect the decision, but wanted to share my sorrow. I hope the following aspect was considered in the name change discussion:

How likely is it that in the next, say 10 years again there will be such a dramatic rework of the font that causes incompatibilities to earlier versions? There have been other versions before (0.x to 3.x), that didn’t require renaming. Will the font name now change every time the global version makes a big step – even when there are no compatibility issues to former versions? Or will there be e.g. Source Serif 4, version 6.080?

In my opinion a version number in the font name is not forward compatible. I would have liked to see Adobe only ditch the “Pro” and instead used “Source Serif” as the base name. (JOKE:) Then “Source Serif Neue” or “Source Serif Next” is still free for a backwards incompatible version in 10 or 15 years.

**Comment by frankrolf** [comment]
I think the naming change will lead to a more consistent experience, which is much preferable to document reflow.
As far as I know, no software really considers the font version number when fonts in a document are replaced/updated.

- there was a (what could be considered breaking) change from version 1.014 to version 1.017: the weight range was increased, and the weight of the heavier-than Regular styles was increased significantly. 1.014 was considered young enough to be replaced silently – nobody could have known that the three-weight version would stick around on Google Fonts for 5 more years. A name change would have been a good idea then.
- vertical metrics changed from version 2 to version 3, caused by the addition of Vietnamese diacritics. Users replacing Source Serif with the latest version would potentially see their line spacing change.
- major updates to commercial Adobe fonts have adopted the same naming principle, such as Minion 3 – which is clearly different from Minion Pro (and Minion MM before that) – this has been positively received
- there will not be a Source Serif 4 v`6.403`.  The `4` corresponds to the major version number. When a significant update warrants incrementing the major version number, the family name will also move to Source Serif 5.

**Comment by charakterziffer** [comment]
Thank you very much, Frank, for the explanation. I was not aware, that the metrics would change that often. Meanwhile I also found the thread https://github.com/google/fonts/issues/1307, where the weight change of Montserrat caused much upset. And while I still don’t like version numbers in font names that much, I completely agree that it’s a practicable solution until software honors font versioning. Thanks again for your effort!

**Comment by fitojb** [comment]
Unfortunately this blocks upgrading this font in LibreOffice in the future. I am not comfortable breaking users’ templates and documents each time a font name change is done.

**Comment by frankrolf** [comment]
@fitojb Thats the whole idea. This way, you're also not inadvertently breaking people's documents. 
It would be nice if you'd consider adding the new font family to Libre Office anyway – at a later point.￼

**Comment by fitojb** [comment]
Do you really expect to change things like the line height, now that diacritics support is complete? Minor advance width changes are livable, but this is too much.

**Comment by frankrolf** [comment]
@fitojb Diacritics support is never complete! ;-) (really – virtually all other issues are about adding more diacritics).
Although the scope of the family will extend significantly, there was not really an urgent reason to change the vertical metrics with that extension. I edited a handful of important glyphs (such as the inferior parentheses) to fall into the range of the previous metrics (see commit above). This means there will be no change in line height from Source Serif Pro to Source Serif 4.

**Comment by frankrolf** [comment]
Source Serif 4 has been released:
https://github.com/adobe-fonts/source-serif/releases/tag/4.004R
See further explanation on this name change in the release notes linked above.
