### ISSUE TITLE
Bad kerning OG in small caps

### ISSUE THREAD

**Issue by PaulPichaureau** [adobe-fonts/source-serif#83]
Hi,

I've noticed a bad kerning between O and G in the small caps version of the regular font (weight 400). See picture below.

![Image 15-11-2020 à 19 35](https://user-images.githubusercontent.com/1976614/99193569-1e227480-277a-11eb-9ecf-f8a83ee146d4.jpg)

In my opinion, the kerning between O and G should be reduced.

Thank you for your excellent and much appreciated work !

**Comment by frankrolf** [comment]
Oh no! And I thought I was a kerning OG! ;-)
Will be fixed.

**Comment by frankrolf** [comment]
This has been fixed in the latest release: https://github.com/adobe-fonts/source-serif/releases/tag/4.004R
