### ISSUE TITLE
Lowercased last names in credits

### ISSUE THREAD

**Issue by twardoch** [adobe-fonts/source-serif#91]
On https://adobe-fonts.github.io/source-serif/ many last names are lowercased. 

<img width="461" alt="scr- 2021-03-04 at 02 37 02" src="https://user-images.githubusercontent.com/519108/109897184-9c0b7c80-7c92-11eb-9e74-6f71bc10bd57.png">

**Comment by frankrolf** [comment]
I have a feeling there's something going on on your end. Are they lowercased in the source code?

![image](https://user-images.githubusercontent.com/2049645/109932840-ff190580-7cca-11eb-9728-4c4e5ab60cdf.png)

**Comment by frankrolf** [comment]
Can’t reproduce this anywhere. Please share your setup and check possible browser extensions you might have installed. Could your result have been auto-translated?

<img width="1542" alt="Screen Shot 2021-03-04 at 10 04 02" src="https://user-images.githubusercontent.com/2049645/109939083-fe836d80-7cd0-11eb-8102-b0cc4a9d9314.png">

**Comment by frankrolf** [comment]
Yes. Not my bug.

https://user-images.githubusercontent.com/2049645/109939469-6043d780-7cd1-11eb-8e25-aee1e5f458bb.mov
