### ISSUE TITLE
Source Serif Mono?

### ISSUE THREAD

**Issue by lf94** [adobe-fonts/source-serif#94]
I think the Adobe Source fonts are absolutely great. Recently (past 6 months) I've switched to Go Mono because of its serif nature and the benefits of serifs. A month or so ago I discovered Source Serif, but today, I was met with disappointment: this isn't a monospace font!

Are there any plans to make one out of it, or somehow turn it into one easily?

Thanks! And keep up the great work!

**Comment by frankrolf** [comment]
Thanks for the compliment! :-)

This needs a bit more background info, so please bear with me.
In a nutshell: Monospaced Serif fonts are uncommon – for a reason.

I can see that the Go fonts you’re referring to are actually just Lucida. From the outset, Lucida was planned as a low-resolution design, and it has a slab-serifed version, which was drawn for a very specific purpose – faxing: https://en.wikipedia.org/wiki/Lucida#Lucida_Fax
From that, a monospaced variant called “Lucida Typewriter” was created: https://en.wikipedia.org/wiki/Lucida#Lucida_Typewriter_Serif
Lucida Typewriter seems to be the basis for the Go font.

The style of Source Serif is quite different from Lucida: Lucida has Slab Serifs added to a Sans body, Source Serif has a different letter construction based on a historical model, generally higher contrast and pointier serifs.
As such, it does not lend itself to creating a monospaced version. The Latin alphabet is not monospaced by nature, so a monospaced Serif font will always look somewhat odd.

That said, it is common to find monospaced Latin letters in conjunction with CJK fonts – as Latin full-width characters.
Publico Text Mono is an exploration of this: https://commercialtype.com/catalog/publico_text_mono
You will find the Latin glyphs I’m referring to in Source Han Serif: https://source.typekit.com/source-han-serif/

For that design I have indeed drawn Full-, Half- and even Quarter-width Latin alphabets, but they are not useful as a monospaced font for coding. In the Source world, the recommended font for doing that is Source Code: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.038R-ro%2F1.058R-it%2F1.018R-VAR

To answer your questions specifically:
> Are there any plans to make [a monospaced font out of Source Serif]?
No plans.

> [Is there a way to] somehow turn [Source Serif] into [a monospaced design] easily?
No. It would be a considerable amount of work, and the result would’t look good or work well as a coding font.

I hope these responses don’t disappoint you – rather, I hope you understand why this would not be a very fruitful endeavor.

**Comment by lf94** [comment]
Thank you very much for your detailed response :) I very much understand. It explains why Lucida / Go Mono is somewhat decent as a monospace serif font too.

**Comment by RuixiZhang42** [comment]
@lf94 If you are looking for a quality monospaced serif design, I&nbsp;recommend [*Triplicate*](https://mbtype.com/fonts/triplicate/) designed by Matthew Butterick (the &ldquo;Code&rdquo; variant in particular). The italics are wonderful IMO, and not long ago I&nbsp;even found use for the roman small caps! *Disclaimer:&nbsp;I&nbsp;do not profit from advertising for Matthew. I&rsquo;m simply a satisfied customer.*

Typographica had a review on *Triplicate* (previously called *FB&nbsp;Alix*) if you are interested in learning more: https://typographica.org/typeface-reviews/fb-alix/

**Comment by lf94** [comment]
I've found PT Mono to be nice, but that one too seems very nice :D I'll check it out, thank you!

**Comment by lf94** [comment]
@RuixiZhang42 I can't seem to find the Code variant specifically on that website. Could you directly link it here, or describe where it can be found please?

**Comment by RuixiZhang42** [comment]
@lf94 It’s in the “features” tab, or this link: https://mbtype.com/fonts/triplicate/features.html
Code mode is implemented as Stylistic Set&nbsp;2. But the purchase also comes with fonts that have code mode glyphs in the default positions, so you can install different versions if your layout program doesn’t support advance OpenType features.

Matthew did an update on all his fonts between October 2020 and March 2021 (I&nbsp;think). I&nbsp;must admit it has become more difficult to find documentations for these features. I&nbsp;had a PDF specimen for Triplicate from 2019 that contained the following page (but the page was no longer in the 2021 PDF specimen! Also I&nbsp;think the slashed zero was gone?):
> ![triplicate-spec](https://user-images.githubusercontent.com/39968857/114330096-f1973c80-9b0e-11eb-8912-7e91dfd2f6bb.png)

**Comment by RuixiZhang42** [comment]
@lf94 BTW, if you like his other fonts, it may be cheaper to license combo from his “Practical Typography” website.
